
export default new Map([
["src/content/docs/architecture/roadmap-boundaries.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Farchitecture%2Froadmap-boundaries.mdx&astroContentModuleFlag=true")],
["src/content/docs/architecture/system-design.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Farchitecture%2Fsystem-design.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/docker-and-persistence.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Fdocker-and-persistence.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/install-and-build.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Finstall-and-build.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/run-local.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Frun-local.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/client-usage.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fclient-usage.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/server-operations.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fserver-operations.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/transactions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Ftransactions.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/overview.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Foverview.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cli-reference.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcli-reference.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/persistence-and-recovery.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fpersistence-and-recovery.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/runtime-guards.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fruntime-guards.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/security-model.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fsecurity-model.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/wire-protocol.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fwire-protocol.mdx&astroContentModuleFlag=true")],
["src/content/docs/why-vaylix.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fwhy-vaylix.mdx&astroContentModuleFlag=true")]]);
		